version: '3.8'

services:
  app:
    build: .
    container_name: telegram-promo-bot
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      bash -c "
      uvicorn api.main:app --host 0.0.0.0 --port 8000
      "
